const STRIPE_KEY = 'sk_test_51Ne9coLBjUooMXI1FT8uA7IAPuXHcmNhhVs6lbV3V2BmSPmstt3NFqANSyZ7HFuhia3eILzG55N5O4SwAvojSBvZ00CLOcfY3E';
const GOOGLE_API = 'AIzaSyDGf0EXb4I0BQoE2t_IsJmkOJXYTc0S5bA';
module.exports={
    STRIPE_KEY:STRIPE_KEY,
    GOOGLE_API:GOOGLE_API,
};
