export const SET_USER = 'SET_USER';
export const SET_AUCTION_IMAGES = 'SET_AUCTION_IMAGES';
export const SET_AUCTION_DETAILS = 'SET_AUCTION_DETAILS';
export const SET_BID_DETAILS = 'SET_BID_DETAILS'





